import Foundation
import Observation

@MainActor
@Observable
final class DropQueue {
    struct Item: Identifiable {
        enum Status {
            case waiting
            case processing(String)
            case done(String?)
            case failed(String)
        }

        let id = UUID()
        let url: URL
        let preset: ProcessingPreset
        let compare: Bool
        let addFades: Bool
        let trimSilence: Bool
        let renameOriginal: Bool
        let resolution: OutputResolution
        let stages: StudioBoothStages
        var status: Status = .waiting
    }

    private(set) var items: [Item] = []
    private(set) var series: [LoudnessSeries] = []
    /// Seconds of silence trimmed per source, keyed by sourceID, for surfacing a note.
    private(set) var trimmedSecondsBySource: [UUID: Double] = [:]
    private(set) var latestTransaction: BatchTransaction?
    private(set) var isUndoing = false
    private(set) var isCancelling = false
    private(set) var undoError: String?
    var compareMode = false
    private var isRunning = false
    private var processingTask: Task<Void, Never>?
    private var transactionOperations: [UndoOperation] = []

    /// Called whenever a batch finishes; receives the number of failed or partial items.
    var onAllDone: ((_ failures: Int) -> Void)?
    var onStateChange: (() -> Void)?
    var onWillBeginBatch: (() -> Void)?
    var onWillUndo: (() -> Void)?

    var isIdle: Bool { !isRunning && !isUndoing && !isCancelling }
    var canCancel: Bool { isRunning && !isCancelling }

    /// A finished batch is present and the app can be returned to its initial
    /// drop-screen state.
    var canReset: Bool { !series.isEmpty && isIdle }

    /// Whether the most recent finished batch was a Compare fan-out.
    var wasCompareBatch: Bool { items.contains(where: \.compare) }

    /// Files generated by the latest batch (everything that isn't an original).
    var generatedFileCount: Int { series.filter { !$0.isOriginal }.count }

    func enqueue(
        _ urls: [URL],
        preset: ProcessingPreset,
        compare: Bool,
        addFades: Bool,
        trimSilence: Bool,
        renameOriginal: Bool,
        resolution: OutputResolution,
        stages: StudioBoothStages
    ) {
        if !isRunning {
            onWillBeginBatch?()
            items = []
            series = []
            trimmedSecondsBySource = [:]
            latestTransaction = nil
            transactionOperations = []
            undoError = nil
        }
        onStateChange?()
        items.append(contentsOf: urls.map {
            Item(
                url: $0,
                preset: preset,
                compare: compare,
                addFades: addFades,
                trimSilence: trimSilence,
                renameOriginal: renameOriginal,
                resolution: resolution,
                stages: stages
            )
        })
        runIfNeeded()
    }

    /// Removes the comparison artifact files created during a compare run and
    /// resets the queue. Used when the user switches away from Compare so the
    /// generated versions that are no longer shown don't linger on disk.
    func discardComparison() {
        guard isIdle else { return }
        for operation in latestTransaction?.operations ?? transactionOperations {
            if case .delete(let url) = operation {
                try? FileManager.default.removeItem(at: url)
            }
        }
        series = []
        items = []
        latestTransaction = nil
        transactionOperations = []
        undoError = nil
        trimmedSecondsBySource = [:]
        onStateChange?()
    }

    /// Returns the app to its initial drop-screen state.
    ///
    /// Generated (non-original) outputs are always kept on disk. When
    /// `deleteOriginals` is true, the original-series files are removed:
    /// - Compare: there is one untouched original per source; it is left in
    ///   place and only the generated variants are kept — pass `false` here and
    ///   delete the variants via `deleteGeneratedFiles()` instead.
    /// - Single replace mode: the "original" is the backup copy, so deleting it
    ///   removes the backup while the louder file stays at the source path.
    /// - Single separate mode: the original is the untouched source file.
    func reset(deleteOriginals: Bool) {
        guard isIdle else { return }
        onWillUndo?()
        if deleteOriginals {
            for original in series where original.isOriginal {
                try? FileManager.default.removeItem(at: original.url)
            }
        }
        clearToInitialState()
    }

    /// Deletes every generated (non-original) artifact produced by the latest
    /// batch, then returns to the initial drop-screen state. Used by Compare
    /// reset where the user chooses to discard all generated comparison files.
    func deleteGeneratedFiles() {
        guard isIdle else { return }
        onWillUndo?()
        for generated in series where !generated.isOriginal {
            try? FileManager.default.removeItem(at: generated.url)
        }
        clearToInitialState()
    }

    private func clearToInitialState() {
        series = []
        items = []
        latestTransaction = nil
        transactionOperations = []
        undoError = nil
        trimmedSecondsBySource = [:]
        onStateChange?()
    }


    /// terminated, every artifact this batch produced is removed, any replaced
    /// originals are restored, and the queue returns to the idle/empty state.
    func cancelProcessing() {
        guard canCancel else { return }
        isCancelling = true
        onStateChange?()
        processingTask?.cancel()
    }

    private func rollbackCancelledBatch() {
        // Reverse anything already committed by completed items in this batch.
        try? applyUndo(transactionOperations)
        transactionOperations = []
        latestTransaction = nil
        series = []
        items = []
        undoError = nil
        trimmedSecondsBySource = [:]
    }

    func undoLatestBatch() {
        guard let transaction = latestTransaction, !transaction.isEmpty, isIdle else { return }
        onWillUndo?()
        isUndoing = true
        onStateChange?()
        undoError = nil

        do {
            try preflight(transaction.operations)
            try applyUndo(transaction.operations)
            latestTransaction = nil
            transactionOperations = []
            series = []
            items = []
            trimmedSecondsBySource = [:]
        } catch {
            undoError = error.localizedDescription
        }
        isUndoing = false
        onStateChange?()
    }

    private func preflight(_ operations: [UndoOperation]) throws {
        for operation in operations {
            switch operation {
            case .restore(let originalURL, let backupURL):
                guard FileManager.default.fileExists(atPath: originalURL.path) else {
                    throw LouderError.processingFailed(
                        "Cannot undo because \(originalURL.lastPathComponent) is missing"
                    )
                }
                guard FileManager.default.fileExists(atPath: backupURL.path) else {
                    throw LouderError.processingFailed(
                        "Cannot undo because \(backupURL.lastPathComponent) is missing"
                    )
                }
            case .delete(let url):
                guard FileManager.default.fileExists(atPath: url.path) else {
                    throw LouderError.processingFailed(
                        "Cannot undo because \(url.lastPathComponent) is missing"
                    )
                }
            }
        }
    }

    private func applyUndo(_ operations: [UndoOperation]) throws {
        // Comparison artifacts are safe to delete first. Replacements are then restored.
        for operation in operations {
            if case .delete(let url) = operation {
                try FileManager.default.removeItem(at: url)
            }
        }
        for operation in operations {
            if case .restore(let originalURL, let backupURL) = operation {
                try FileManager.default.removeItem(at: originalURL)
                try FileManager.default.moveItem(at: backupURL, to: originalURL)
            }
        }
    }

    private func update(id: UUID, status: Item.Status) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].status = status
        onStateChange?()
    }

    private func updateProgress(id: UUID, message: String) {
        guard let index = items.firstIndex(where: { $0.id == id }),
              case .processing = items[index].status else {
            return
        }
        items[index].status = .processing(message)
        onStateChange?()
    }

    private func runIfNeeded() {
        guard !isRunning else { return }
        isRunning = true
        onStateChange?()
        processingTask = Task {
            while !Task.isCancelled, let next = items.first(where: {
                if case .waiting = $0.status { return true } else { return false }
            }) {
                let id = next.id
                update(id: id, status: .processing("Starting…"))
                do {
                    let result = try await Processor.process(
                        next.url,
                        preset: next.preset,
                        compare: next.compare,
                        addFades: next.addFades,
                        trimSilence: next.trimSilence,
                        renameOriginal: next.renameOriginal,
                        resolution: next.resolution,
                        stages: next.stages
                    ) { message in
                        Task { @MainActor [weak self] in
                            self?.updateProgress(id: id, message: message)
                        }
                    }
                    if Task.isCancelled {
                        // Include this finished item's artifacts in the batch
                        // transaction so rollbackCancelledBatch() fully reverses
                        // it — including restoring any replaced original.
                        transactionOperations.append(contentsOf: result.undoOperations)
                        break
                    }
                    series.append(contentsOf: result.series)
                    if let trimmed = result.trimmedSeconds,
                       let sourceID = result.series.first?.sourceID {
                        trimmedSecondsBySource[sourceID] = trimmed
                    }
                    transactionOperations.append(contentsOf: result.undoOperations)
                    let detail = result.warnings.isEmpty
                        ? nil
                        : result.warnings.joined(separator: "\n")
                    update(id: id, status: .done(detail))
                } catch {
                    if Task.isCancelled { break }
                    update(id: id, status: .failed(error.localizedDescription))
                }
            }

            processingTask = nil
            isRunning = false

            if isCancelling {
                rollbackCancelledBatch()
                isCancelling = false
                onStateChange?()
                return
            }

            latestTransaction = BatchTransaction(operations: transactionOperations)
            onStateChange?()
            let failures = items.filter {
                switch $0.status {
                case .failed: true
                case .done(let detail): detail != nil
                case .waiting, .processing: false
                }
            }.count
            onAllDone?(failures)
        }
    }
}
